config/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("works.urls")),
    # path('', include('django.contrib.auth.urls')),
]

works/urls.py
from django.urls import path

from . import views

app_name = "works"

urlpatterns = [
    path("login/", views.Login.as_view(), name="login"),
    path("logout/", views.Logout.as_view(), name="logout"),
    path("index/", views.index, name="index"),
    path("pulldown-access/", views.pulldown_access, name="pulldown-access"),
    path("admin-login/", views.AdminLogin.as_view(), name="admin-login"),
    path("admin-login/user-list/", views.user_list, name="user-list"),
    path(
        "admin-login/user-result/<int:user_id>/", views.user_result, name="user-result"
    ),
]

works/models.py
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from django.contrib.auth.validators import UnicodeUsernameValidator
from django.core.validators import MinLengthValidator, RegexValidator
from django.db import models

from .functions import decryption, encryption


class UserManager(BaseUserManager):
    """カスタムユーザーマネージャー"""

    def create_user(self, user_no, password=None):
        if not user_no:
            raise ValueError("社員番号を入力してください。")

        # user = self.model(
        #     email=self.normalize_email(email),
        # )
        user = self.model(user_no=user_no)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_staffuser(self, user_no, password):
        user = self.create_user(
            user_no,
            password=password,
        )
        user.staff = True
        user.save(using=self._db)
        return user

    def create_superuser(self, user_no, password):
        user = self.create_user(
            user_no,
            password=password,
        )
        user.staff = True
        user.admin = True
        user.save(using=self._db)
        return user


class User(AbstractBaseUser):
    """カスタムユーザーモデル"""

    # RegexValidatorを使用して正規表現でのバリデーションをかける
    num_regex = RegexValidator(regex=r"\d{4}", message=("4桁の社員番号を入力してください。"))
    user_no = models.CharField(
        verbose_name="社員番号",
        max_length=4,
        help_text="4桁で番号を入力。",
        unique=True,
        error_messages={
            "unique": "既に使用されている番号です",
        },
        validators=[MinLengthValidator(4), num_regex],  # 最低の文字数を検証・設定
    )
    username_validators = UnicodeUsernameValidator()  # ユーザーネームに関する検証
    username = models.CharField(
        verbose_name="ユーザー名",
        max_length=150,
        help_text="150文字以下の文字や数字、一部の記号で入力してください。",
        validators=[username_validators],
    )
    active = models.BooleanField(default=True)
    staff = models.BooleanField(default=False)
    admin = models.BooleanField(default=False)

    USERNAME_FIELD = "user_no"

    # User.objectsを呼び出すための変数
    objects = UserManager()

    def save(self, **kwargs):
        try:
            """保存する前にユーザーネームの暗号化"""
            self.username = encryption(self.username)
        except:
            # 既に暗号化されている場合は一度復号化してから再度暗号化して保存
            self.username = encryption(decryption(self.username))
        super(User, self).save(**kwargs)

    def __str__(self):
        return self.user_no

    def has_perm(self, perm, obj=None):
        return self.admin

    def has_module_perms(self, app_label):
        return self.admin

    @property
    def is_staff(self):
        return self.staff

    @property
    def is_admin(self):
        return self.admin

    @property
    def is_active(self):
        return self.active


class Work(models.Model):
    """勤怠情報テーブル"""

    # models.PROTECTによって関連付けられているUserが削除されてもその関連先オブジェクトが存在する限り削除されない
    user_id = models.ForeignKey(User, verbose_name="社員ID", on_delete=models.PROTECT)
    date = models.DateField(verbose_name="日付")
    start_time = models.TimeField(
        verbose_name="出勤時間",
        null=True,
        blank=True,
    )
    end_time = models.TimeField(verbose_name="退勤時間", null=True, blank=True)
    break_time = models.TimeField(
        verbose_name="休憩時間", default="01:00:00", null=True, blank=True
    )
    comment = models.TextField(verbose_name="業務内容", null=True, blank=True)

    def __str__(self):
        return str(self.date)


# Create your models here.

works/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm
from django.utils import timezone

from .models import Work


class LoginForm(AuthenticationForm):
    """
    既存の認証用フォームを使用して自作フォームを作成
    メモ：
    カスタムユーザーフィールドで定義したヘルプテキストや
    バリデーションエラー等のメッセージがこの継承クラスに
    反映されていないようなので、時間がある時に公式ドキュメントを
    見直す。
    """

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # カスタムユーザーモデルは「user_no」を認証にしているが、ここでは「user_no」が「username」としてキーになっている
        self.fields["username"].widget.attrs["class"] = "form-control rounded-pill"
        self.fields["username"].widget.attrs["placeholder"] = "社員番号"
        self.fields["password"].widget.attrs["class"] = "form-control rounded-pill"
        self.fields["password"].widget.attrs["placeholder"] = "パスワード"


class WorkForm(forms.ModelForm):
    """モーダル用のフォーム"""

    class Meta:
        model = Work
        fields = (
            "user_id",
            "date",
            "start_time",
            "end_time",
            "break_time",
            "comment",
        )
        widgets = {
            "user_id": forms.NumberInput(
                attrs={
                    "id": "modal_user_id",
                    "name": "modal_user_id",
                }
            ),
            "date": forms.TextInput(
                attrs={
                    "id": "modal_date",
                    "name": "modal_date",
                }
            ),
            "start_time": forms.TextInput(
                attrs={
                    "class": "form-control",
                    "placeholder": "出勤",
                    "id": "modal_start_time",
                    "name": "modal_start_time",
                }
            ),
            "end_time": forms.TextInput(
                attrs={
                    "class": "form-control",
                    "placeholder": "退勤",
                    "id": "modal_end_time",
                    "name": "modal_end_time",
                }
            ),
            "break_time": forms.TextInput(
                attrs={
                    "class": "form-control",
                    "placeholder": "休憩",
                    "id": "modal_break_time",
                    "name": "modal_break_time",
                }
            ),
            "comment": forms.Textarea(
                attrs={
                    "class": "form-control",
                    "placeholder": "業務内容",
                    "id": "modal_comment",
                    "name": "modal_comment",
                    "row": "5",
                }
            ),
        }


class EveryMonthForm(forms.Form):
    """
    月別リストのプルダウン用フォーム
    """

    # 本日までのデータを取得（未来のデータを取得しないため）
    date = (
        Work.objects.order_by("-date")
        .filter(date__lte=timezone.now().date())
        .values_list("date")
    )
    # 年/月に変換し保管
    date_list = [d[0].strftime("%Y/%m") for d in date]
    # 上記のorder_by("-date")の並び順を固定で、リストのindex番号12番目までを取得（過去１２か月分）
    date_unique = list(sorted(set(date_list), key=date_list.index))[:12]
    # choicesに渡すため要素をタプルで囲み一時保管
    date_list_tuple = [(d, d) for d in date_unique]
    # リストからタプルにして準備完了
    dates = tuple(date_list_tuple)

    date_pulldown = forms.ChoiceField(
        choices=dates,
        widget=forms.widgets.Select(
            attrs={"class": "form-select rounded-pill mb-3", "id": "date_pulldown"}
        ),
    )

works/views.py
from django.contrib.auth import authenticate
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LoginView, LogoutView
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.utils import timezone

from .forms import EveryMonthForm, LoginForm, WorkForm
from .functions import create_user_works, month_check
from .models import User, Work


class Login(LoginView):
    """ログイン画面"""

    form_class = LoginForm
    template_name = "works/login.html"
    redirect_authenticated_user = True  # ログイン状態で/login/にアクセスされた時にリダイレクト先へ飛ばす

    def form_invalid(self, form):
        """検証失敗後の処理"""
        # 各フィールドのclass属性にis-invalid（失敗）もしくわis-valid（クリア）を追記する
        auth_result = authenticate(
            username=form.data["username"], password=form.data["password"]
        )
        # 管理者かどうかのブール値を出力するための変数
        user = User.objects.filter(user_no=form.data["username"]).values_list("admin")
        for field in form:
            if field.errors:
                # フォームが未入力のフィールド
                # 入力されていないフィールドはclass属性にis-invalidを追記する
                form[field.name].field.widget.attrs["class"] += " is-invalid"
            elif auth_result is None:
                # 認証に失敗したらinvalid
                form[field.name].field.widget.attrs["class"] += " is-invalid"
            elif user.get()[0] is False:
                # 管理者でなければinvalid
                form[field.name].field.widget.attrs["class"] += " is-invalid"

        return self.render_to_response(self.get_context_data(form=form))


class Logout(LogoutView):
    """ログアウト"""

    template_name = "works/index"


# 一般ユーザーが直接アクセスしてきた際にログイン画面へとリダイレクトされるようにする
@login_required(login_url="/login/")
def index(request):
    """
    日報登録＆月別リスト画面
    """

    # 最新の月データが存在するかチェック用の関数
    month_check(request.user.id)

    # 当月の勤怠情報を表示するためのデータを取得
    user_works = create_user_works(request.user.id)

    # モーダルの更新用フォームとして使用するクエリ
    work = get_object_or_404(
        Work, user_id=request.user.id, date=timezone.now().date().strftime("%Y-%m-%d")
    )
    # モーダルフォームの作成
    modal_form = WorkForm(instance=work)
    if request.method == "POST":
        """
        モーダルがポストされた時の処理
        """
        # 新たにPOSTされたデータを使用して更新用データを取得
        work = get_object_or_404(
            Work,
            # データの取得に必要なユーザーID
            user_id=request.POST["user_id"],
            # POSTされた日付を割り当てる
            date=request.POST["date"],
        )
        modal_form = WorkForm(request.POST, instance=work)
        if modal_form.is_valid():  # 検証成功した場合
            if modal_form.initial["start_time"]:  # 出勤データが既にある場合は退勤フォームをテスト
                """
                カスタムユーザーを使っているため、バリデーションエラー等の
                エラーメッセージやvalidatoreの実装のしかたが分からないので
                各フォームを１つずつテストをしてエラーを出している
                """
                if modal_form.initial["end_time"]:  # 退勤データが既にある場合は休憩フォームをテスト
                    if modal_form.data["break_time"]:  # 休憩フォームに入力されている場合はセーブでリダイレクト
                        modal_form.save()
                        return redirect("works:index")
                    else:  # 休憩フォームが未入力だった場合はエラー
                        modal_form["break_time"].field.widget.attrs[
                            "class"
                        ] += " is-invalid"
                else:
                    if modal_form.data["end_time"]:  # 退勤フォームが入力されている場合はセーブでリダイレクト
                        modal_form.save()
                        return redirect("works:index")
                    else:  # 退勤フォームが未入力だった場合はエラー
                        modal_form["end_time"].field.widget.attrs[
                            "class"
                        ] += " is-invalid"

            else:  # 出勤データが無かった場合
                if modal_form.data["start_time"]:  # 出勤フォームに入力されている場合はセーブでリダイレクト
                    modal_form.save()
                    return redirect("works:index")
                else:  # 出勤フォームが入力されていなかった場合エラー
                    modal_form["start_time"].field.widget.attrs[
                        "class"
                    ] += " is-invalid"
        else:  # 検証失敗でフォームが未入力だった場合
            for field in modal_form:
                if field.errors:
                    # フォームが未入力のフィールド
                    # 入力されていないフィールドはclass属性にis-invalidを追記する
                    modal_form[field.name].field.widget.attrs["class"] += " is-invalid"

    # 月で切り替えるためのプルダウンフォーム
    pulldown_form = EveryMonthForm()

    context = {
        "user_works": user_works,
        "pulldown_form": pulldown_form,
        "modal_form": modal_form,
        "work": work,
    }
    return render(request, "works/index.html", context)


def pulldown_access(request):
    """
    予約リスト画面のプルダウンによる非同期処理
    メモ：
    プルダウンが押された際に非同期処理としてサクセスされるので、
    返り値をJsonResponseで返し、javascriptの規則でデータが処理されるので、
    Djangoのテンプレートフィルタで簡単に出来ることを以下後半の部分で曜日や時間、コメントの制限を
    実装している。
    コードが汚すぎるしせっかくDjangoを使っているので、テンプレートフィルタが使える方法を今後模索していく。
    """
    # javascriptから送られてきた要素を取得
    select_value = request.POST.get("month_val")
    if not select_value:  # 値が存在しなければデフォルトの月別リスト画面を表示
        return redirect("works:index")
    # 「/」に合わせてsplitする
    select_value = select_value.split("/")
    result_query = Work.objects.order_by("date").filter(
        user_id=request.user.id,  # 社員画面ではログイン中のidを参照
        date__year=select_value[0],
        date__month=select_value[1],
    )
    # javascriptでイテレーションするためにリスト内辞書に変換
    query_list = list(result_query.values())
    # 表記を日本人向け（デフォルトのフォーマット）にするため、曜日を設定
    weeks = {
        "Monday": "（月）",
        "Tuesday": "（火）",
        "Wednesday": "（水）",
        "Thursday": "（木）",
        "Friday": "（金）",
        "Saturday": "（土）",
        "Sunday": "（日）",
    }
    # デフォルトのフォーマットに合わせるため、各辞書のキーに代入
    for query in query_list:
        query["week"] = (
            query["date"].strftime("%d") + weeks[query["date"].strftime("%A")]
        )
        # 時間データのあるなし処理。ない場合は「null」となるので「''」を代入する
        if query["start_time"]:
            query["start_time"] = query["start_time"].strftime("%H:%M")
        else:
            query["start_time"] = " "
        if query["end_time"]:
            query["end_time"] = query["end_time"].strftime("%H:%M")
        else:
            query["end_time"] = " "
        if query["break_time"]:
            query["break_time"] = query["break_time"].strftime("%H:%M")
        else:
            query["break_time"] = " "
        if query["comment"]:
            if len(query["comment"]) >= 40:
                query["comment"] = query["comment"][:40] + "..."
            else:
                pass
        else:
            query["comment"] = " "

    return JsonResponse({"query_list": query_list})


class AdminLogin(LoginView):
    """管理者ログイン画面"""

    form_class = LoginForm
    template_name = "works/admin_login.html"
    redirect_authenticated_user = True  # ログイン状態で/admin-login/にアクセスされた時にリダイレクト先へ飛ばす
    redirect_field_name = "user-list"  # リダイレクトり先が「/admin-login/user-list/」となる

    def get_redirect_url(self):
        """
        フォームの認証、検証共に成功した後の処理
        リダイレクト先の戻り値指定
        """
        redirect_to = self.redirect_field_name
        return redirect_to

    def post(self, request, *args, **kwargs):
        """
        POSTパラメータを押された際の処理
        管理者でなければ無効にする
        """
        form = self.get_form()
        if form.is_valid():  # フォームの検証
            auth_result = authenticate(
                username=form.data["username"], password=form.data["password"]
            )
            if auth_result:  # 認証されれば成功
                user = User.objects.filter(user_no=form.data["username"]).values_list(
                    "admin"
                )
                if user.get()[0]:  # 管理者かどうか
                    return self.form_valid(form)
                else:
                    # 管理者以外だった場合のエラーメッセージ
                    form.add_error("username", "認証に失敗しました。")
                    return self.form_invalid(form)
            else:  # 認証されなければ失敗
                return self.form_invalid(form)

        return self.form_invalid(form)

    def form_invalid(self, form):
        """検証失敗後の処理"""
        # 各フィールドのclass属性にis-invalid（失敗）もしくわis-valid（クリア）を追記する
        auth_result = authenticate(
            username=form.data["username"], password=form.data["password"]
        )
        # 管理者かどうかのブール値を出力するための変数
        user = User.objects.filter(user_no=form.data["username"]).values_list("admin")
        for field in form:
            if field.errors:
                # フォームが未入力のフィールド
                # 入力されていないフィールドはclass属性にis-invalidを追記する
                form[field.name].field.widget.attrs["class"] += " is-invalid"
            elif auth_result is None:
                # 認証に失敗したらinvalid
                form[field.name].field.widget.attrs["class"] += " is-invalid"
            elif user.get()[0] is False:
                # 管理者でなければinvalid
                form[field.name].field.widget.attrs["class"] += " is-invalid"

        return self.render_to_response(self.get_context_data(form=form))


@login_required(login_url="/admin-login/")
def user_list(request):
    """社員一覧"""
    if request.user.admin is False:
        return redirect("works:index")
    users = User.objects.all()
    context = {"users": users}
    return render(request, "works/user_list.html", context)


@login_required(login_url="/admin-login/")
def user_result(request, user_id):
    """日報登録＆月別リスト"""

    # 最新の月データが存在するかチェック用の関数
    month_check(user_id)

    # 当月の勤怠情報を表示するためのデータを取得
    user_works = create_user_works(user_id)

    work = get_object_or_404(
        Work, user_id=user_id, date=timezone.now().date().strftime("%Y-%m-%d")
    )
    modal_form = WorkForm(instance=work)
    if request.method == "POST":
        post_data = request.POST
        # 新たにPOSTされたデータを使用して更新用データを取得
        edit_work = get_object_or_404(Work, user_id=user_id, date=post_data["date"])
        modal_form = WorkForm(request.POST, instance=edit_work)
        if modal_form.is_valid():
            modal_form.save()

templates/works/admin_login.html
<!-- extendsはテンプレートの最初のタグである必要があります。 -->
{% extends 'works/base.html' %}
{% load static %}

<!-- 管理者用ログイン画面のバックグラウンドカラーをsuccessカラーに変更 -->
{% block body-color %}bg-success{% endblock %}

{% block content %}
<!-- 管理者専用ログインフォーム -->
<form class="border rounded bg-white form-login" method="post" action="{% url 'works:admin-login' %}" novalidate>{% csrf_token %}
  <h1 class="h3 my-3">Login</h1>
  <!-- 管理者以外がログインを試みた際に表示されるエラー文 -->
  {% for error in form.non_field_errors %}
  {{ error }}
  {% endfor %}

  {% for field in form %}
  <div class="mb-3 pt-3">
    {{ field }}
    <div class="invalid-feedback">
      {{ field.errors.0 }}
    </div>
  </div>
  {% endfor %}
  <button type="submit" class="btn btn-primary text-white rounded-pill px-5 my-4">ログイン</button>
  <input type="hidden" name="next" value="{{ next }}">
</form>

<!-- Option 1: Bootstrap Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
{% endblock %}

templates/works/login.html
<!-- extendsはテンプレートの最初のタグである必要があります。 -->
{% extends 'works/base.html' %}
{% load static %}

{% block content %}
<!-- ログインフォーム -->
<form class="border rounded bg-white form-login" method="post" action="{% url 'works:login' %}" novalidate>{% csrf_token %}
  <h1 class="h3 my-3">Login</h1>
  {% for field in form %}
  <div class="md-3 pt-3">
    {{ field }}
    <div class="invalid-feedback">
      {{ field.errors.0 }}
    </div>
  </div>
  {% endfor %}
  <button type="submit" class="btn btn-primary text-white rounded-pill px-5 my-4">ログイン</button>
  <input type="hidden" name="next" value="{{ next }}">
</form>

<!-- Option 1: Bootstrap Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

{% endblock %}

templates/works/user_list.html
<!-- extendsはテンプレートの最初のタグである必要があります。 -->
{% extends 'works/base.html' %}
{% load static functions %}

<!-- 管理者用月別リストのバックグラウンドカラーをsuccessカラーに変更 -->
{% block body-color %}bg-success{% endblock %}

{% block content %}
<form class="border rounded bg-white form-user-list">
  <h1 class="h3 my-3">社員一覧</h1>

  <!-- 社員一覧テーブル -->
  <table class="table">
    <thead>
      <tr class="bg-light">
	<th scope="col">社員番号</th>
	<th scope="col">社員名</th>
	<th scope="col">権限</th>
      </tr>
    </thead>
    <tbody>
      {% for user in users %}
      <tr>
	<th scope="row">{{ user.user_no }}</th>
	<!-- decryptionフィルターでユーザーネームを復号化している -->
	<td><a href="{% url 'works:user-result' user.id %}">{{ user.username | decryption }}</a></td>
	<td scope="row">{% if user.admin %}管理者{% endif %}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</form>

<!-- Option 1: Bootstrap Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
{% endblock %}

templates/works/user_result.html
<!-- extendsはテンプレートの最初のタグである必要があります。 -->
{% extends 'works/base.html' %}
{% load static %}

<!-- 管理者用月別リスト画面のバックグラウンドカラーをsuccessカラーに変更 -->
{% block body-color %}bg-success{% endblock %}

{% block content %}
<form class="border rounded bg-white form-time-table">
  <h1 class="h3 my-3">月別リスト（{{ work.user_id }}）</h1>

  <!-- 編集ボタンの表示に必要なブロック -->
  <div id="admin" hidden>{{ request.user.admin }}</div>

  <!-- 月を切り替えるプルダウン -->
  <div class="float-start">
    {{ pulldown_form.date_pulldown }}
  </div>
  <!-- 社員一覧に戻るボタン -->
  <div class="float-end">
    <a href="{% url 'works:user-list' %}"><button type="button" class="btn btn-secondary rounded-pill px-5">社員一覧に戻る</button></a>
  </div>

  <table class="table">
    <thead>
      <tr class="bg-light">
	<th scope="col">日</th>
	<th scope="col">出勤</th>
	<th scope="col">退勤</th>
	<th scope="col">休憩</th>
	<th scope="col">業務内容</th>
	<th scope="col"></th>
      </tr>
    </thead>
    <tbody id="table-body">
      {% for user_work in user_works %}
      <tr>
	<th scope="row">{{ user_work.date | date:"j (l)" | cut:"曜日" }}</th>
	<td>{{ user_work.start_time | default:" "}}</td>
	<td>{{ user_work.end_time | default:" " }}</td>
	<td>{{ user_work.break_time | default:" " }}</td>
	<td>{{ user_work.comment | default:" " | truncatechars:"40" }}</td> <!-- 文字数を40字で切り詰め -->
	<td><button type="button" class="btn btn-default h-auto py-0" data-bs-toggle="modal" data-bs-target="#exampleModal" data-day="{{ user_work.date }}"><i class="fa-solid fa-pencil" id="pencil-icon"></i></button></td>
	<td hidden>{{ user_work.user_id }}</td>
	<td hidden>{{ user_work.date | date:"Y-m-d" }}</td>
	<td hidden>{{ user_work.id }}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</form>

<!-- Modal -->
<form method="post" action="{% url 'works:user-result' work.user_id %}">{% csrf_token %}
  <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
	<div class="modal-header">
	  <p></p>
	  <h5 class="modal-title" id="exampleModalLabel">日報登録</h5>
	  <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
	</div>
	<div class="modal-body">
	  <div class="container">
	    <div class="alert alert-primary" role="alert">
	      <span id="modal_day">{{ work.date | date:"n/j (l)" | cut:"曜日" }}</span>
	    </div>
	    <div hidden>
	      {{ modal_form.user_id }}
	      {{ modal_form.date }}
	    </div>
	    <div class="row">
	      <div class="col">
		<div class="input-group">
		  {{ modal_form.start_time }}
		  <button type="button" class="input-group-text" id="start_btn">打刻</button>
		</div>
	      </div>
	      <div class="col">
		<div class="input-group">
		  {{ modal_form.end_time }}
		  <button type="button" class="input-group-text" id="end_btn">打刻</button>
		</div>
	      </div>
	      <div class="col">
		<div class="input-group">
		  {{ modal_form.break_time }}
		</div>
	      </div>
	    </div>
	    <div class="mb-3 pt-3">
	      {{ modal_form.comment }}
	    </div>
	  </div>
	</div>
	<div class="modal-footer">
	  <button type="submit" class="btn btn-primary text-white rounded-pill px-5">登録</button>
	</div>
      </div>
    </div>
  </div>
</form>

<!-- Option 1: Bootstrap Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

<!-- jQuery -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>

<!-- Original JavaScript -->
<script src="{% static 'js/select.js' %}" type="text/javascript"></script>

<script>
  // 出勤用打刻ボタン処理
  $('#start_btn').click(function() {
    const now = new Date();
    const hour = now.getHours().toString().padStart(2, '0');
    const minute = now.getMinutes().toString().padStart(2, '0');
    $('#modal_start_time').val(hour+':'+minute+':'+'00');
  })

// 退勤用打刻ボタン処理
$('#end_btn').click(function() {
  const now = new Date();
  const hour = now.getHours().toString().padStart(2, '0');
  const minute = now.getMinutes().toString().padStart(2, '0');
  $('#modal_end_time').val(hour+':'+minute+':'+'00');
})

// 各日報データの編集ボタン用の処理
$('#exampleModal').on('show.bs.modal', function(event) {
  var button = $(event.relatedTarget)
  var target_day = button.data('day')

  // 編集ボタンが押されたら対処データを取得し代入する処理
  var day = button.closest('tr').children('th')[0].innerText
  var start_time = button.closest('tr').children('td')[0].innerText
  var end_time = button.closest('tr').children('td')[1].innerText
  var break_time = button.closest('tr').children('td')[2].innerText
  var comment = button.closest('tr').children('td')[3].innerText
  var user_id = button.closest('tr').children('td')[5].innerText
  var target_day = button.closest('tr').children('td')[6].innerText

  // 取得したデータをモーダルの各欄に設定
  $('#modal_day').text(day)
  $('#modal_start_time').val(start_time)
  $('#modal_end_time').val(end_time)
  $('#modal_break_time').val(break_time)
  $('#modal_comment').val(comment)
  $('#modal_user_id').val(user_id)
  $('#modal_date').val(target_day)
})

</script>
{% endblock %}